### ISSUE TITLE
Not all gradation output waveforms available with PCA9955B

### ISSUE THREAD

**Issue by Flashmueller** [teddokano/LEDDriver_NXP_Arduino#1] opened 2023-05-23 08:54 UTC
Hi.
First off all , thank you for that gorgeous library. 👍 

I want to use the gradation control in single shot mode to only dimm leds up and keep them on forever.
From the [datasheet ](https://www.nxp.com/docs/en/data-sheet/PCA9955B.pdf) on page 29 i learned, that this can be accomplished if the HOLD_ON / HOLD_OFF bits are set to zero in the HOLD_CNTL_GRP register.

I found that these two bits are [hard coded to 1](https://github.com/teddokano/LEDDriver_NXP_Arduino/blob/main/src/GradationControl.cpp#LL71C2-L71C67) in the set_gradation function.

If I'm not missing something i would like to contribute and send an PR to make these two bits accessible.

Two approaches came to my mind:
1. Set the bits based on parameters "on" and "off" (set the according bit to 1 if a time is given for on/off, or zero, if no holding time is given).
2. Add the bits to the function as separate parameter and assign default values.

Optically there would be no difference for these two approaches. The only thing that behaves differently is the START-bit readback from the function. Maybe you can have a look in the datasheet and make a decission which solution would be more appropriate for your library.

kind regards

**Comment by teddokano** [comment] 2023-05-23 19:39
Hi, 

Thank you for interested in the library. 
As you pointed out, I didn't make interface to set those bits. 

I appreciate your suggestion and I prefer to have the option 2.
Because..

The hold-on/off bits still have meanings even if the hold-on/off time is zero. Please refer to figure 9 in the [datasheet](https://www.nxp.com/docs/en/data-sheet/PCA9955B.pdf). 
For instance, in case of 5 and 7, it shows difference of Hold-ON bit disable/enable effect. To get waveform of case 7 with hold_time = 0, the Hold-ON bit needed to be enabled. 
The Hold-OFF bit is similar (case 1 and 9). 

The Hold-ON bit behavior with hold_time = 0 is confirmed by following code. 
- Channel 0 is assigned to group 0 and channel 5 is assigned to group 1. 
- Group 0 has setting of Ramp-UP: disabled, **Hold-ON: enabled** in `dataR[2]`
- Group 1 has setting of Ramp-UP: disabled, **Hold-ON: disabled** in `dataB[2]`
- After the gradation control is started for both groups, the group 1 (channel 5) will be kept OFF. 

I'm looking forward to seeing your PR 😉

```cpp
#include <PCA9955B.h>
#include <GradationControl.h>

PCA9955B ledd;

void setup() {
  Serial.begin(9600);
  Serial.println("\n***** Hello, PCA9955B! *****");

  Wire.begin();
  ledd.begin(1.0, PCA9955B::ARDUINO_SHIELD);

  GradationControl gradcR = GradationControl(&ledd, 0); //  Gradation group 0
  GradationControl gradcB = GradationControl(&ledd, 1); //  Gradation group 1
  gradcR.add_channel(0);  //  Assign channel 0 to group 0
  gradcB.add_channel(5);  //  Assign channel 5 to group 1
  ledd.pwm(0, 1.0);       //  Set PWM output
  ledd.pwm(5, 1.0);       //  Set PWM output

  //gradcR.set_gradation(1.0, 1.0); //  Set peak current to 100% and ramp-time to 1.0 second
  //gradcB.set_gradation(1.0, 1.0); //  Set peak current to 100% and ramp-time to 1.0 second

  uint8_t dataR[] = { 0x40, 0x0F, 0xC0, 0xFF }; // Ramp-UP: disabled, Hold-ON: enabled
  uint8_t dataB[] = { 0x40, 0x0F, 0x40, 0xFF }; // Ramp-UP: disabled, Hold-ON: disabled
  ledd.reg_access(PCA9955B::RAMP_RATE_GRP0, dataR, sizeof(dataR));
  ledd.reg_access(PCA9955B::RAMP_RATE_GRP1, dataB, sizeof(dataB));

  gradcR.start();         //  Start group 0
  gradcB.start();         //  Start group 1
}

void loop() {
  //  do nothing from MCU
}

```

**Closed as completed** 2023-05-24 23:11 UTC
